# register-deployed-artifact
Use this GitHub Action (GHA) for artifact traceability: inform CloudBees Unify that an artifact version has been deployed.
To learn more about working with artifacts in CloudBees Unify, refer to the deployed artifacts documentation.

== Prerequisites

Set up CloudBees Unify and GitHub Actions to work together, providing key features of CloudBees Unify to GitHub Actions workflows.
Refer to link:https://docs.cloudbees.com/docs/cloudbees-platform/latest/github-actions/gha-getting-started[Getting started with GitHub Actions integration] for more information.

== Inputs
[cols="22%a,15%a,15%a,48%a",options="header"]
.Input details
|===
| Input name
| Data type
| Required?
| Description

| cloudbees-url
| string
| false
| URL of CloudBees Unify API. Defaults to `https://api.cloudbees.io`.

| target-environment
| string
| true
| Deployment environment. Environment must be created in CloudBees Unify before using it in this action.

| labels
| string
| false
| Comma-separated labels for this deployment

| artifact-id
| string
| false
| ID of the artifact, generated by the register-build-artifact action. Either this or artifact-url **must be present**.

| artifact-url
| string
| false
| URL of the deployed artifact. Either this or artifact-id **must be present**.
|===

== Outputs
This action produces no output

== Usage examples

=== Basic example

[source,yaml]
----
    permissions:
      id-token: write
      contents: read
    steps:
      - name: register-deployment-step
        uses: cloudbees-io-gha/register-deployed-artifact@v1
        with:
          target-environment: pre-prod
          labels: v1.0.0, rc1
          artifact-id: 87ace777-ab20-4867-ac3f-ad5c28f46a29
----

=== Full workflow and run example

Running this workflow creates an artifact that is reported to CloudBees Unify, and then that artifact is deployed.

.Example GitHub Actions workflow YAML file
[.collapsible]
--

[source, yaml,role="default-expanded"]
----
name: GHA Workflow

on:
  - workflow_dispatch

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Compile Code
        run: echo "Compiling..."

      - name: Produce Binary
        run: echo "Generating binary..."

      - name: Push binary
        run: echo "Pushing Binary to ECR..."

      - name: Register Build Artifacts in CloudBees Unify
        uses: cloudbees-io-gha/register-build-artifact@v3
        id: go-action
        with:
          name: "gha-artifact-step"
          version: 1.0.0
          url: "docker.io/example:latest"
          digest: sha256:1234567890abcdef123456123456abcdef789078907890abcdefabcdef123456
          label: For testing
          type: docker

      - name: Deploy artifact
        run: echo 'Deploying Build ArtifactId ${{ steps.go-action.outputs.cbp_artifact_id }}'

      - name: Register deployment
        uses: cloudbees-io-gha/register-deployed-artifact@v1
        with:
          target-environment: pre-prod
          labels: For testing
          artifact-id: ${{ steps.go-action.outputs.cbp_artifact_id }}
----
--

After the run completes, CloudBees Unify displays the artifact information on the *Deployments* tab on the *Run details* page.
